// A shareable safety card: a plain-text plan and a portrait PNG that a hiker
// can send to someone staying home. Pure drawing + pure text, no dependencies.

function km(m) { return (m / 1000).toFixed(2) + " km"; }
function dur(minutes) {
  const m = Math.max(0, Math.round(minutes));
  const h = Math.floor(m / 60);
  return h > 0 ? h + "h " + String(m % 60).padStart(2, "0") + "m" : m + "m";
}
function clock(date) {
  if (!(date instanceof Date) || Number.isNaN(date.getTime())) return "--:--";
  return String(date.getHours()).padStart(2, "0") + ":" + String(date.getMinutes()).padStart(2, "0");
}
function day(date) {
  if (!(date instanceof Date) || Number.isNaN(date.getTime())) return "";
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  return date.getDate() + " " + months[date.getMonth()];
}

const VERDICT_COLOR = { go: "#34d399", caution: "#fbbf24", turn: "#fb7185", past: "#f43f5e" };
const VERDICT_TEXT = {
  go: "On track for daylight",
  caution: "Tight on daylight",
  turn: "Turn around now",
  past: "Past turnaround",
};

// Plain text summarising the plan, suitable for a check-in message.
export function buildPlanText(m) {
  const lines = [];
  lines.push("LASTLIGHT TRIP PLAN");
  lines.push(m.routeName + " (" + (m.mode === "loop" ? "thru / loop" : "out and back") + ")");
  lines.push("Distance " + km(m.distanceM) + " · Ascent " + Math.round(m.ascentM) + " m");
  lines.push("Start " + day(m.startTime) + " " + clock(m.startTime) +
    " · Daylight " + clock(m.sunrise) + " to " + clock(m.sunset));
  if (m.turnaroundDistanceM != null) {
    lines.push("Turnaround: " + km(m.turnaroundDistanceM) + " (reach it by " + clock(m.deadline) + ")");
    lines.push("Back at the trailhead by " + clock(m.backBy));
  } else if (m.dusk) {
    lines.push("Must finish by " + clock(m.dusk));
  }
  if (m.bailouts && m.bailouts.length) {
    lines.push("Bailouts: " + m.bailouts.slice(0, 3).map(function (b) {
      return b.name + " (" + dur(b.minutes) + (b.reachable === false ? ", too late" : "") + ")";
    }).join(", "));
  }
  if (m.partySize && m.partySize > 1) lines.push("Party of " + m.partySize + " · pace set by the slowest member");
  lines.push("");
  lines.push("Generated by Lastlight. Check conditions and use your own judgement.");
  return lines.join("\n");
}

function wrap(ctx, text, x, y, maxWidth, lineHeight) {
  const words = String(text).split(" ");
  let line = "";
  let yy = y;
  for (let i = 0; i < words.length; i++) {
    const test = line ? line + " " + words[i] : words[i];
    if (ctx.measureText(test).width > maxWidth && line) {
      ctx.fillText(line, x, yy);
      line = words[i];
      yy += lineHeight;
    } else {
      line = test;
    }
  }
  if (line) ctx.fillText(line, x, yy);
  return yy;
}

// Draw the portrait share card at 1080x1350.
export function drawShareCard(canvas, m) {
  const W = 1080;
  const H = 1350;
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext("2d");
  const accent = VERDICT_COLOR[m.verdict] || "#ffb347";

  const bg = ctx.createLinearGradient(0, 0, 0, H);
  bg.addColorStop(0, "#0e1a33");
  bg.addColorStop(0.55, "#0a1222");
  bg.addColorStop(1, "#060a12");
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, W, H);

  const glow = ctx.createRadialGradient(W * 0.82, 150, 10, W * 0.82, 150, 560);
  glow.addColorStop(0, "#ff8a3d66");
  glow.addColorStop(1, "#ff8a3d00");
  ctx.fillStyle = glow;
  ctx.fillRect(0, 0, W, 760);

  // ridge silhouette
  ctx.beginPath();
  ctx.moveTo(0, H * 0.62);
  ctx.lineTo(W * 0.18, H * 0.5);
  ctx.lineTo(W * 0.34, H * 0.58);
  ctx.lineTo(W * 0.52, H * 0.44);
  ctx.lineTo(W * 0.72, H * 0.56);
  ctx.lineTo(W, H * 0.46);
  ctx.lineTo(W, H);
  ctx.lineTo(0, H);
  ctx.closePath();
  ctx.fillStyle = "#0a1220";
  ctx.fill();

  // brand
  ctx.fillStyle = "#e9eefc";
  ctx.font = "700 40px ui-sans-serif, system-ui, sans-serif";
  ctx.fillText("LASTLIGHT", 72, 116);
  ctx.fillStyle = "#8ea3c7";
  ctx.font = "400 24px ui-sans-serif, system-ui, sans-serif";
  ctx.fillText("know your turnaround", 72, 154);

  // verdict pill
  ctx.font = "700 24px ui-sans-serif, system-ui, sans-serif";
  const vtext = VERDICT_TEXT[m.verdict] || "Plan";
  const vw = ctx.measureText(vtext).width + 56;
  ctx.fillStyle = accent + "26";
  ctx.beginPath();
  ctx.roundRect(72, 196, vw, 52, 26);
  ctx.fill();
  ctx.fillStyle = accent;
  ctx.fillText(vtext, 100, 231);

  // route name
  ctx.fillStyle = "#e9eefc";
  ctx.font = "700 58px ui-sans-serif, system-ui, sans-serif";
  const nameBottom = wrap(ctx, m.routeName, 72, 340, W - 144, 66);

  // big turnaround number
  ctx.fillStyle = "#ffb347";
  ctx.font = "700 150px ui-sans-serif, system-ui, sans-serif";
  const big = m.turnaroundDistanceM != null ? km(m.turnaroundDistanceM) : km(m.distanceM);
  ctx.fillText(big, 72, nameBottom + 190);
  ctx.fillStyle = "#8ea3c7";
  ctx.font = "400 28px ui-sans-serif, system-ui, sans-serif";
  ctx.fillText(m.turnaroundDistanceM != null ? "furthest safe turnaround" : "route length", 76, nameBottom + 232);

  // stat rows
  const stats = [
    ["Distance", km(m.distanceM)],
    ["Ascent", Math.round(m.ascentM) + " m"],
    ["Start", clock(m.startTime)],
    ["Back by", m.backBy ? clock(m.backBy) : clock(m.dusk)],
  ];
  let sy = nameBottom + 320;
  for (let i = 0; i < stats.length; i++) {
    ctx.fillStyle = "#93a7ca";
    ctx.font = "400 30px ui-sans-serif, system-ui, sans-serif";
    ctx.fillText(stats[i][0], 76, sy);
    ctx.fillStyle = "#e9eefc";
    ctx.font = "600 34px ui-monospace, monospace";
    const val = stats[i][1];
    ctx.fillText(val, W - 76 - ctx.measureText(val).width, sy);
    sy += 62;
  }

  // mini elevation profile
  const px = 72;
  const pw = W - 144;
  const py = H - 330;
  const ph = 150;
  if (m.profile && m.profile.points && m.profile.points.length > 1) {
    const pts = m.profile.points;
    let min = Infinity;
    let max = -Infinity;
    for (let i = 0; i < pts.length; i++) { min = Math.min(min, pts[i].ele); max = Math.max(max, pts[i].ele); }
    const span = max - min || 1;
    const total = m.profile.distanceM || 1;
    ctx.beginPath();
    ctx.moveTo(px, py + ph);
    for (let i = 0; i < pts.length; i++) {
      ctx.lineTo(px + (pts[i].dist / total) * pw, py + ph - ((pts[i].ele - min) / span) * ph);
    }
    ctx.lineTo(px + pw, py + ph);
    ctx.closePath();
    const pg = ctx.createLinearGradient(0, py, 0, py + ph);
    pg.addColorStop(0, "#ffb347cc");
    pg.addColorStop(1, "#ff8a3d10");
    ctx.fillStyle = pg;
    ctx.fill();
    ctx.beginPath();
    for (let i = 0; i < pts.length; i++) {
      const x = px + (pts[i].dist / total) * pw;
      const y = py + ph - ((pts[i].ele - min) / span) * ph;
      if (i === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y);
    }
    ctx.strokeStyle = "#ffd9a8";
    ctx.lineWidth = 3;
    ctx.stroke();
    // turnaround marker
    if (m.turnaroundDistanceM != null) {
      const tx = px + (m.turnaroundDistanceM / total) * pw;
      ctx.setLineDash([8, 8]);
      ctx.beginPath();
      ctx.moveTo(tx, py - 16);
      ctx.lineTo(tx, py + ph);
      ctx.strokeStyle = "#ffb347";
      ctx.lineWidth = 3;
      ctx.stroke();
      ctx.setLineDash([]);
    }
  }

  // footer
  ctx.fillStyle = "#61789f";
  ctx.font = "400 24px ui-sans-serif, system-ui, sans-serif";
  ctx.fillText("github.com/JovanXin/lastlight", 72, H - 60);
  ctx.textAlign = "right";
  ctx.fillText(day(m.startTime) + " " + clock(m.startTime), W - 72, H - 60);
  ctx.textAlign = "left";
  return canvas;
}
